### ISSUE TITLE
Private access token settings

### ISSUE THREAD

**Issue by bengarvey** [singer-io/tap-github#1]
The tap works when I use these settings
![screen shot 2017-04-22 at 7 13 57 am](https://cloud.githubusercontent.com/assets/1342331/25303968/7610ce7e-272b-11e7-9145-a33a21ceb974.png)

But not these
![screen shot 2017-04-22 at 7 14 06 am](https://cloud.githubusercontent.com/assets/1342331/25303972/83f825dc-272b-11e7-843b-f70f411662bb.png)

I'd prefer to grant read-only access to the token. Is this just an issue of how granular github's permissions are?

**Comment by cmerrick** [comment]
the tap just reads commits and issues from the given repository, so this is surprising.  Did you get an error message from the github API?

**Comment by bengarvey** [comment]
This was the error. It looks like github returned an error and we tried run pop on a string.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tap-github", line 11, in <module>
    load_entry_point('tap-github==0.1.0', 'console_scripts', 'tap-github')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tap_github.py", line 124, in main
    do_sync(config, state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tap_github.py", line 90, in do_sync
    state = get_all_commits(repo_path, state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tap_github.py", line 49, in get_all_commits
    commit.pop('author', None)
AttributeError: 'str' object has no attribute 'pop'
```
