### ISSUE TITLE
can't import data to stitch 

### ISSUE THREAD

**Issue by ifokeev** [singer-io/tap-github#11]
```
INFO Sending batch with 31 messages for table reviews to https://api.stitchdata.com/v2/import/batch
CRITICAL Error persisting data for table "reviews": Invalid JSON schema: key null: expected type is one of JSONObject, found: Boolean
Traceback (most recent call last):
  File "tap-github/tap_github.py", line 201, in <module>
    main()
  File "tap-github/tap_github.py", line 198, in main
    do_sync(config, state)
  File "tap-github/tap_github.py", line 163, in do_sync
    state = get_all_pull_requests(repo_path, state)
  File "tap-github/tap_github.py", line 51, in get_all_pull_requests
    singer.write_records('files', files)
  File "/usr/local/lib/python3.6/site-packages/singer/messages.py", line 223, in write_records
    write_record(stream_name, record)
  File "/usr/local/lib/python3.6/site-packages/singer/messages.py", line 212, in write_record
    time_extracted=time_extracted))
  File "/usr/local/lib/python3.6/site-packages/singer/messages.py", line 201, in write_message
    sys.stdout.write(format_message(message) + '\n')

```

**Comment by nick-mccoy** [comment]
Hey @ifokeev can you retry this with the updated tap and see if you're still getting this error?

**Comment by nick-mccoy** [comment]
This should be fixed in the new version, so I am closing the issue.
