### ISSUE TITLE
GitHub limits pagination for some resources which breaks replicating comments when repository has lots of comments

### ISSUE THREAD

**Issue by jamo** [singer-io/tap-github#61]
I was trying to copy the GitHub comments dataset for `gatsbyjs/gatsby` to BigQuery, but it seems that once there are enough comments, the ETL process fails with the following error:
```
CRITICAL 422 Client Error: Unprocessable Entity for url: https://api.github.com/repositories/36040894/issues/comments?sort=updated&direction=asc&page=1334
```

It appears, that GitHub allows pagination only for 1333 pages for https://api.github.com/repositories/36040894/issues/comments?sort=updated&direction=asc&page=1334 

### snippet from the extraction logs log:
<details>

```
2019-03-13 20:23:19,823Z    tap - INFO HTTP request to "comments" endpoint took 1.157s, returned status code 200
2019-03-13 20:23:20,033Z    tap - INFO HTTP request to "comments" endpoint took 0.173s, returned status code 422
2019-03-13 20:23:20,034Z    tap - INFO replicated 749 records from "comments" endpoint
2019-03-13 20:23:20,034Z    tap - CRITICAL 422 Client Error: Unprocessable Entity for url: https://api.github.com/repositories/36040894/issues/comments?sort=updated&direction=asc&page=1334
2019-03-13 20:23:20,034Z    tap - Traceback (most recent call last):
2019-03-13 20:23:20,034Z    tap -   File "tap-env/bin/tap-github", line 10, in <module>
2019-03-13 20:23:20,034Z    tap -     sys.exit(main())
2019-03-13 20:23:20,034Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 225, in wrapped
2019-03-13 20:23:20,034Z    tap -     return fnc(*args, **kwargs)
2019-03-13 20:23:20,034Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_github.py", line 556, in main
2019-03-13 20:23:20,035Z    tap -     do_sync(args.config, args.state, catalog)
2019-03-13 20:23:20,035Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_github.py", line 529, in do_sync
2019-03-13 20:23:20,035Z    tap -     state = sync_func(stream_schema, repo, state, mdata)
2019-03-13 20:23:20,035Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_github.py", line 412, in get_all_comments
2019-03-13 20:23:20,035Z    tap -     'https://api.github.com/repos/{}/issues/comments?sort=updated&direction=asc{}'.format(repo_path, query_string)
2019-03-13 20:23:20,035Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_github.py", line 102, in authed_get_all_pages
2019-03-13 20:23:20,035Z    tap -     r.raise_for_status()
2019-03-13 20:23:20,035Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
2019-03-13 20:23:20,035Z    tap -     raise HTTPError(http_error_msg, response=self)
2019-03-13 20:23:20,036Z    tap - requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repositories/36040894/issues/comments?sort=updated&direction=asc&page=1334
```

</details>

**Comment by bengarvey** [comment]
Same issue here.

**Comment by bengarvey** [comment]
@jamo Maybe we can start from `desc` and get the rest paging backwards lol

**Comment by jamo** [comment]
I was able to hack my way through this by manually checking the last successful insert from a failed run, and manually edited the pip package code to use that as the `since` time for the request. And then repeat that until you can once successfully complete the sync for this table.

This might cause data duplication (and it's easy with this module anyways) so I do recommend deduplicating the data in the SQL queries or create a view with the dedup

Then it should use bookmarks properly for consecutive runs.

**Comment by dbshah1212** [comment]
This error occurs when we use the URL `https://api.github.com/repositories/36040894/issues/comments` and it hits the limit of 40000 records.

Where as in tap-github below URL used:
https://api.github.com/repos/{owner}/{repo}/issues/comments
Which is as per the docs(https://docs.github.com/en/rest/issues/comments#list-issue-comments-for-a-repository), which is not breaking while running the tap for more than 40000 data.

**Comment by dbshah1212** [comment]
As there is no reply from long time, closing this isssue.
